<?php

namespace AppBundle\Repository;

/**
 * LokalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LokalRepository extends \Doctrine\ORM\EntityRepository
{
}
