<?php

namespace AppBundle\Repository;

/**
 * UzytkonikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UzytkonikRepository extends \Doctrine\ORM\EntityRepository
{
}
