<?php

namespace AppBundle\Repository;

/**
 * WydarzenieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WydarzenieRepository extends \Doctrine\ORM\EntityRepository
{
}
