<?php

namespace AppBundle\Repository\Model;

/**
 * UzytkownikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UzytkownikRepository extends \Doctrine\ORM\EntityRepository
{
}
